stop trying to dry the nf cleanup action and get access token diretly with client creds

diff --git a/.github/actions/nf-network-cleanup/action.yml b/.github/actions/nf-network-cleanup/action.yml
--- a/.github/actions/nf-network-cleanup/action.yml
+++ b/.github/actions/nf-network-cleanup/action.yml
@@ -4,9 +4,6 @@ inputs:
   network_name:
     description: Name of the network to delete
     required: true
-  access_token:
-    description: NetFoundry access token
-    required: true
 
 runs:
   using: composite
@@ -15,18 +12,32 @@ runs:
       shell: bash
       run: |
         set -o pipefail
+
+        set +o xtrace  # mask the oauth access token
+        OAUTH_RESP="$(
+          curl --silent --fail --location --request POST \
+            https://netfoundry-production-xfjiye.auth.us-east-1.amazoncognito.com/oauth2/token \
+            --header 'Content-Type: application/x-www-form-urlencoded' \
+            --user "${{ secrets.NF_API_CLIENT_ID_FOR_GITHUB }}:${{ secrets.NF_API_CLIENT_PW_FOR_GITHUB }}" \
+            --data-urlencode 'grant_type=client_credentials'
+        )"
+        if [[ -z "$OAUTH_RESP" ]]; then
+          echo "ERROR: OAUTH_RESP is empty" >&2
+          exit 1
+        fi
+        ACCESS_TOKEN="$(echo $OAUTH_RESP | jq -r .access_token)"
+        if [[ -z "$ACCESS_TOKEN" ]]; then
+          echo "ERROR: ACCESS_TOKEN is empty" >&2
+          exit 1
+        fi
+        echo "::add-mask::$ACCESS_TOKEN"
         set -o xtrace
 
         # get network ID
-        NF_ACCESS_TOKEN="${{ inputs.access_token }}"
-        if [[ -z "$NF_ACCESS_TOKEN" ]]; then
-            echo "ERROR: NF_ACCESS_TOKEN is empty" >&2
-            exit 1
-        fi
         NF_NETWORK_LIST="$(curl --silent --fail --location --request GET \
             https://gateway.production.netfoundry.io/core/v3/networks \
             --header 'Content-Type: application/json' \
-            --header "Authorization: Bearer $NF_ACCESS_TOKEN"
+            --header "Authorization: Bearer $ACCESS_TOKEN"
         )"
         if [[ -z "$NF_NETWORK_LIST" ]]; then
             echo "ERROR: NF_NETWORK_LIST is empty" >&2
@@ -42,7 +53,7 @@ runs:
             NF_NETWORK_STATUS="$(curl --silent --fail --location --request DELETE \
                 "https://gateway.production.netfoundry.io/core/v3/networks/$NF_NETWORK_ID" \
                 --header 'Content-Type: application/json' \
-                --header "Authorization: Bearer ${{ inputs.access_token }}"
+                --header "Authorization: Bearer $ACCESS_TOKEN"
             )"
             if [[ -z "$NF_NETWORK_STATUS" ]]; then
                 echo "ERROR: NF_NETWORK_STATUS is empty" >&2
